
server:
  port: 8081 #服务注册中心端口号
eureka:
  server:
    #自动剔除无效服务
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: eurekaAliyunService.com #服务注册中心IP地址
    prefer-ip-address: true

  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
spring:
  security:
    user:
      name: admin
      password: Admin123